var hcpcs_alias = 
   [{"hcpcs": "80100", "hcpcs_name":"Drug Screen, Multiple"},
   {"hcpcs": "80101", "hcpcs_name":"Drug Screen, Single"},
   {"hcpcs": "80102", "hcpcs_name":"Drug Confirmation"},
   {"hcpcs": "80152", "hcpcs_name":"Amitriptyline"},   
   {"hcpcs": "80154", "hcpcs_name":"Benzodiazepines"},
   {"hcpcs": "80160", "hcpcs_name":"Desipramine"},
   {"hcpcs": "80166", "hcpcs_name":"Doxepin"},
   {"hcpcs": "80174", "hcpcs_name":"Imipramine"},
   {"hcpcs": "80182", "hcpcs_name":"Nortriptyline"},
   {"hcpcs": "80184", "hcpcs_name":"Phenobarbital"},
   {"hcpcs": "80188", "hcpcs_name":"Primidone"},
   {"hcpcs": "80299", "hcpcs_name":"Quantitation, Other"},
   {"hcpcs": "82055", "hcpcs_name":"Alcohol, Not Breath"},
   {"hcpcs": "82075", "hcpcs_name":"Alcohol, Breath"},   
   {"hcpcs": "82145", "hcpcs_name":"Amphetamine"},
   {"hcpcs": "82205", "hcpcs_name":"Barbiturates"},
   {"hcpcs": "82491", "hcpcs_name":"Chromatography"},   
   {"hcpcs": "82520", "hcpcs_name":"Cocaine"},
   {"hcpcs": "82542", "hcpcs_name":"Column Chromatography"},
   {"hcpcs": "83789", "hcpcs_name":"Mass Spectrometry"},
   {"hcpcs": "83805", "hcpcs_name":"Meprobamate"},
   {"hcpcs": "83840", "hcpcs_name":"Methadone"},
   {"hcpcs": "83925", "hcpcs_name":"Opiates"},
   {"hcpcs": "83992", "hcpcs_name":"Phencyclidine (PCP)"},
   {"hcpcs": "84022", "hcpcs_name":"Phenothiazine"},
   {"hcpcs": "84311", "hcpcs_name":"Spectro-photometry, Other"}]
